## Chapter 2: Linear Algebra (PyTorch Notebook)

### 2.1 Scalars, Vectors, Matrices and Tensors

In [1]:
import torch

**Scalar:**
- A scalar is a single number.

In [2]:
# Scalar

s = torch.tensor(2)
print(f"Scalar s = {s}")

Scalar s = 2


---

**Vector:**
- A vector is an array of numbers.
- The numbers are arranged in an order.
- We can identify each individual number by its index value.

In [3]:
# Vector

x = torch.tensor([10, 20, 30, 40, 50])
print(f"Vector x = {x}")

Vector x = tensor([10, 20, 30, 40, 50])


---

**Matrix:**
- A Matrix is 2D Array of numbers, so each element is identified by two indices instead of just one.

In [4]:
# Matrix

A = torch.full((3, 3), 5)
print(f"Matrix A = \n{A}")

Matrix A = 
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


---

**Tensor:**
- An array of numbers arranged on a regular grid with a variable number of axes is known as a tensor.

In [5]:
# Tensor
T = torch.full((3, 3, 3), 5)
print(f"Tensor T = \n{T}")

Tensor T = 
tensor([[[5, 5, 5],
         [5, 5, 5],
         [5, 5, 5]],

        [[5, 5, 5],
         [5, 5, 5],
         [5, 5, 5]],

        [[5, 5, 5],
         [5, 5, 5],
         [5, 5, 5]]])


---

**Transpose:**
- The transpose of a matrix is the mirror image of the matrix across a diagonal line, called the main diagonal, \
running down and to the right, starting from its upper left corner.

In [6]:
# Transpose of Matrix

A = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

A_transpose = torch.transpose(
    input = A, 
    dim0 = 0, # First dim to be transposed
    dim1 = 1  # Second dim to be transposed
    )

print(f"Original Matrix A: \n{A}\n")
print(f"Transposed Matrix: \n{A_transpose}")

Original Matrix A: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Transposed Matrix: 
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


---

In [7]:
# Matrix-Matrix Addition

A = torch.full((3, 3), 5)
B = torch.full((3, 3), 10)

C = A + B

print(f"Matrix A: \n{A}")
print(f"\nMatrix B: \n{B}")
print(f"\nMatrix C = A + B \n{C}")

Matrix A: 
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

Matrix B: 
tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])

Matrix C = A + B 
tensor([[15, 15, 15],
        [15, 15, 15],
        [15, 15, 15]])


---

In [8]:
# Matrix-Sclar Addition and Multiplication

A = torch.full((3, 3), 5)
scalar1 = 10
scalar2 = 20 

C = A * scalar1 + scalar2


print(f"Matrix A: \n{A}")
print(f"\nscalar1 = {scalar1}")
print(f"scalar2 = {scalar2}")
print(f"\nC = A * scalar1 + scalar2 \n{C}")


Matrix A: 
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

scalar1 = 10
scalar2 = 20

C = A * scalar1 + scalar2 
tensor([[70, 70, 70],
        [70, 70, 70],
        [70, 70, 70]])


---

In [9]:
# Matrix-Vector Addition without Broadcasting

A = torch.full((3, 3), 5)
matrix_x = torch.full((3, 3), 4)

C1 = A + matrix_x 
print("Matrix Vector Addition without Broadcasting")
print(f"\nMatrix A: \n{A}")
print(f"\nmatrix_x: \n{matrix_x}")
print(f"\nC1 = A + matrix_x: \n{C1}")


Matrix Vector Addition without Broadcasting

Matrix A: 
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

matrix_x: 
tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])

C1 = A + matrix_x: 
tensor([[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]])


**Broadcasting:**
- In the above case, we see that the `matrix_x` is essentially a vector `[4, 4, 4]` copied 2 times to form 3 rows.
- We can eliminate this copying, by using broadcasting. 
- Instead, in broadcasting, a single vector is broadcasted (copied) to the rows of the target matrix for the required operation (here - addition).
- Here is an intuitive example of how broadcasting works.

```
                Addition            
                   | --> [5, 5, 5]   [9, 9, 9]
     [4, 4, 4] --> | --> [5, 5, 5] = [9, 9, 9]
                   | --> [5, 5, 5]   [9, 9, 9]
```

In [10]:
# Matrix-Vector Addition with Broadcasting

A = torch.full((3, 3), 5)
vector_x = torch.tensor([4, 4, 4])

C2 = A + vector_x 

print("Matrix Vector Addition with Broadcasting")
print(f"\nMatrix A: \n{A}")
print(f"\nvector_x: \n{vector_x}")
print(f"\nC2 = A + vector_x: \n{C2}")



Matrix Vector Addition with Broadcasting

Matrix A: 
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

vector_x: 
tensor([4, 4, 4])

C2 = A + vector_x: 
tensor([[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]])


---