## 2.2 Multiplying Matrices and Vectors

In [1]:
import torch

**Matrix-Matrix Product**
- For this to defined, **A** must have the same number of columns as **B** has rows.

In [2]:
# Matrix Product

A = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = torch.tensor([
    [3, 4, 7],
    [6, 2, 1],
    [3, 5, 8]
])

C = torch.matmul(A, B)

print(f"Matrix A \n{A}")
print(f"\nMatrix B \n{B}")
print(f"\nMatrix C = AB \n{C}")

Matrix A 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Matrix B 
tensor([[3, 4, 7],
        [6, 2, 1],
        [3, 5, 8]])

Matrix C = AB 
tensor([[ 24,  23,  33],
        [ 60,  56,  81],
        [ 96,  89, 129]])


---

**Hadamard Product**
- It is also called element-wise product where we obtain the product of individual elements of the \
two matrices.

In [3]:
C = torch.mul(A, B)

print(f"Matrix A \n{A}")
print(f"\nMatrix B \n{B}")
print(f"\nHadamard Product \n{C}")

Matrix A 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Matrix B 
tensor([[3, 4, 7],
        [6, 2, 1],
        [3, 5, 8]])

Hadamard Product 
tensor([[ 3,  8, 21],
        [24, 10,  6],
        [21, 40, 72]])


---

**Vector Dot Product**

In [4]:
vector1 = torch.tensor([2, 2, 2])
vector2 = torch.tensor([5, 10, 20])

dot_product = torch.dot(vector1, vector2)

print(f"vector1 \n{vector1}")
print(f"\nvector2 \n{vector2}")
print(f"\nDot Product of A and B \n{dot_product}")

vector1 
tensor([2, 2, 2])

vector2 
tensor([ 5, 10, 20])

Dot Product of A and B 
70


---

### Matrix Product Properties

**Distributive Property**
```
A(B + C) = AB + AC
```

In [5]:
A = torch.full((3, 3), 2)
B = torch.full((3, 3), 3)
C = torch.full((3, 3), 5)

print(f"\nMatrix A: \n{A}")
print(f"\nMatrix B: \n{B}")
print(f"\nMatrix C: \n{C}")

lhs = torch.matmul(A, B+C)
print(f"\nLHS: A(B + C) \n{lhs}")

rhs = torch.matmul(A, B) + torch.matmul(A, C)
print(f"\nRHS: AB + AC \n{rhs}")


Matrix A: 
tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

Matrix B: 
tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])

Matrix C: 
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

LHS: A(B + C) 
tensor([[48, 48, 48],
        [48, 48, 48],
        [48, 48, 48]])

RHS: AB + AC 
tensor([[48, 48, 48],
        [48, 48, 48],
        [48, 48, 48]])


---

**Associative Property**
```
A(BC) = (AB)C
```

In [6]:
A = torch.full((3, 3), 2)
B = torch.full((3, 3), 3)
C = torch.full((3, 3), 5)

print(f"\nMatrix A: \n{A}")
print(f"\nMatrix B: \n{B}")
print(f"\nMatrix C: \n{C}")

lhs = torch.matmul(A, torch.matmul(B, C))
print(f"\nLHS: A(BC) \n{lhs}")

rhs = torch.matmul(torch.matmul(A, B), C)
print(f"\nRHS: (AB)C \n{rhs}")


Matrix A: 
tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

Matrix B: 
tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])

Matrix C: 
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

LHS: A(BC) 
tensor([[270, 270, 270],
        [270, 270, 270],
        [270, 270, 270]])

RHS: (AB)C 
tensor([[270, 270, 270],
        [270, 270, 270],
        [270, 270, 270]])


---

**Non Commutativity of Matrix Multiplication**
```
AB != BA
```

- `AB = BA` can hold true for some cases. 

In [7]:
A = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = torch.tensor([
    [3, 4, 7],
    [6, 2, 1],
    [3, 5, 8]
])

print(f"\nMatrix A: \n{A}")
print(f"\nMatrix B: \n{B}")

print(f"AB \n{torch.matmul(A, B)}")
print(f"BA \n{torch.matmul(B, A)}")


Matrix A: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Matrix B: 
tensor([[3, 4, 7],
        [6, 2, 1],
        [3, 5, 8]])
AB 
tensor([[ 24,  23,  33],
        [ 60,  56,  81],
        [ 96,  89, 129]])
BA 
tensor([[ 68,  82,  96],
        [ 21,  30,  39],
        [ 79,  95, 111]])


---

**Commutativity of Vector Dot Product**
```
x dot y = y dot x
```

In [8]:
vector1 = torch.tensor([2, 2, 2])
vector2 = torch.tensor([5, 10, 20])

dot_product = torch.dot(vector1, vector2)

print(f"vector1 = {vector1}")
print(f"\nvector2 = {vector2}")
print(f"\nvector1 dot vector2 = {torch.dot(vector1, vector2)}")
print(f"\nvector2 dot vector1 = {torch.dot(vector2, vector1)}")

vector1 = tensor([2, 2, 2])

vector2 = tensor([ 5, 10, 20])

vector1 dot vector2 = 70

vector2 dot vector1 = 70


---

**Transpose of a Matrix Product**

$$(AB)^T = B^T A^T$$

In [9]:
A = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = torch.tensor([
    [3, 4, 7],
    [6, 2, 1],
    [3, 5, 8]
])

print(f"\nMatrix A: \n{A}")
print(f"\nMatrix B: \n{B}")

print(f"AB \n{torch.matmul(A, B)}")

print(f"(AB)^T \n{torch.transpose(torch.matmul(A, B), 0, 1)}")

print(f"B^T A^T \n{torch.matmul(torch.transpose(B, 0, 1), torch.transpose(A, 0, 1))}")


Matrix A: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Matrix B: 
tensor([[3, 4, 7],
        [6, 2, 1],
        [3, 5, 8]])
AB 
tensor([[ 24,  23,  33],
        [ 60,  56,  81],
        [ 96,  89, 129]])
(AB)^T 
tensor([[ 24,  60,  96],
        [ 23,  56,  89],
        [ 33,  81, 129]])
B^T A^T 
tensor([[ 24,  60,  96],
        [ 23,  56,  89],
        [ 33,  81, 129]])


---

**Additional Resources**
- [3Blue1Brown Video](https://www.youtube.com/watch?v=XkY2DOUCWMU)
- [Prof. Gilbert Strang Lecture](https://www.youtube.com/watch?v=FX4C-JpTFgY&t=1s)

---