## 2.3 Identity and Inverse Matrices

**Identity Matrix**
- An identity matrix is a matrix that does not change any vector when we multiply that vector by that matrix.
- The structure of identity matrix is to have all the entries along the main diagonal as 1 while all other entires are 0.

In [1]:
import torch

In [2]:
identity_matrix = torch.eye(3)
print(f"A 3x3 Identity Matrix: \n{identity_matrix}")

A 3x3 Identity Matrix: 
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


---

**Matrix Inverse**

The Matrix Inverse `A^-1` is defined as the matrix such that 
$$A^{-1}A = I$$

In [3]:
# Case 1: Inverse Exists

A = torch.tensor([
    [4, -2, 1],
    [5, 0, 3],
    [-1, 2, 6]
    ],
    dtype = torch.float32
)

A_inverse = torch.linalg.inv(A)

print(f"Matrix A: \n{A}")
print(f"\nMatrix A_inverse: \n{A_inverse}")

Matrix A: 
tensor([[ 4., -2.,  1.],
        [ 5.,  0.,  3.],
        [-1.,  2.,  6.]])

Matrix A_inverse: 
tensor([[-0.1154,  0.2692, -0.1154],
        [-0.6346,  0.4808, -0.1346],
        [ 0.1923, -0.1154,  0.1923]])


You can find the mathmatical calculation of the above values [here](https://www.cuemath.com/algebra/inverse-of-a-matrix/) in example 2.

In [4]:
# Case 2: Inverse Does Not Exist
# In this case the function will throw a RuntimeError

A = torch.tensor([
    [4, -2, 1],
    [5, 0, 3],
    [0, 0, 0]
    ],
    dtype = torch.float32
)

A_inverse = torch.linalg.inv(A)

_LinAlgError: linalg.inv: The diagonal element 3 is zero, the inversion could not be completed because the input matrix is singular.

---

**Additional Resources**
- [Prof. Gilbert Strang Video](https://www.youtube.com/watch?v=FX4C-JpTFgY)
- [3Blue1Brown Video](https://www.youtube.com/watch?v=uQhTuRlWMxw)

---