## 2.4 Linear Dependence and Span

For `A^-1` to exist the equation `Ax = b` must have exactly one solution for every value of `b`.  
It is also possible for the system of equations to have no solution or infinitely many solutions for some \
values of `b`.

In [1]:
import torch

In [2]:
A = torch.randn(2, 3, 3)
b = torch.randn(3, 1)
x = torch.linalg.solve(A, b)

In [3]:
print(f"Matrix A: \n{A}")
print(f"\nVector b: \n{b}")

print(f"\nSolution of Ax = b: \n{x}")

Matrix A: 
tensor([[[ 0.8261, -1.3230,  0.7334],
         [ 0.4653, -0.8757, -0.1822],
         [-0.4040, -0.0922,  0.3706]],

        [[ 0.4952, -0.8889, -1.2967],
         [-1.4212,  0.2438,  0.7049],
         [ 0.2650,  0.2260,  0.3242]]])

Vector b: 
tensor([[ 1.1666],
        [ 2.0487],
        [-0.4740]])

Solution of Ax = b: 
tensor([[[-0.1112],
         [-2.0037],
         [-1.8987]],

        [[-0.3782],
         [-9.3851],
         [ 5.3897]]])


---

**Additional Resources**
- [3Blue1Brown Video](https://www.youtube.com/watch?v=k7RM-ot2NWY)
- [Prof. Gilbert Strang Lecture](https://www.youtube.com/watch?v=eeMJg4uI7o0)

---