## 2.5 Norms

- In Machine Learning, we measure the size of a vector using a function called norm.
- On an intuitive level, the norm of a vector `x` measures the distance from the origin to the point `x`.

In [1]:
import torch

**L1 Norm**
- The L1 Norm is commonly used in Machine Learning when the difference between zero and nonzero elements is very important.
- Every time the element of `x` moves away from 0 by a value, the L1 increases by that value.
- In other words, the L1 Norm is just the sum of all the elements of the vector.

In [2]:
x = torch.tensor([2, 4, 6], dtype=float)

l1_norm = torch.linalg.vector_norm(x, ord = 1)

print(f"Vector x: \n{x}")
print(f"\nL1 Norm of x: {l1_norm}")

Vector x: 
tensor([2., 4., 6.], dtype=torch.float64)

L1 Norm of x: 12.0


In [3]:
# Increasing the value of one element of x by 5
x[0] = x[0] + 5

l1_norm = torch.linalg.vector_norm(x, ord = 1)

print(f"Vector x: \n{x}")
print(f"\nL1 Norm of x: {l1_norm}")

Vector x: 
tensor([7., 4., 6.], dtype=torch.float64)

L1 Norm of x: 17.0


The value of L1 Norm also increased by 5.

---

**L2 Norm**
- The L2 Norm is known as the Euclidean Norm, which is simply the Euclidean distance from the origin \
to the point identified by `x`.
- The squared L2 Norm is more convinient to work with mathematically and computationally that the L2 Norm.

In [4]:
x = torch.tensor([2, 4, 6], dtype=float)

l2_norm = torch.linalg.vector_norm(x, ord = 2)

print(f"Vector x: \n{x}")
print(f"\nL2 Norm of x: {l2_norm}")
print(f"\nSquared L2 Norm of x: {l2_norm**2}")

Vector x: 
tensor([2., 4., 6.], dtype=torch.float64)

L2 Norm of x: 7.483314773547883

Squared L2 Norm of x: 56.0


In [5]:
# Internally it is being calculated as follows

torch.sqrt((x[0] - 0)**2 + (x[1] - 0)**2 + (x[2] - 0)**2)

tensor(7.4833, dtype=torch.float64)

---

**Max Norm**
- This norm simplifies to the absolute value of the element with the largest magnitude in the vector.

In [6]:
x = torch.tensor([2, 4, 6], dtype=float)

max_norm = torch.linalg.norm(x, ord = float('inf'))

print(f"Vector x: \n{x}")
print(f"\nMax Norm of x: {l2_norm}")

Vector x: 
tensor([2., 4., 6.], dtype=torch.float64)

Max Norm of x: 7.483314773547883


---

**Additional Resources**
- [NormalizedNerd Video](https://www.youtube.com/watch?v=FiSy6zWDfiA)
- [Prof Gilbert Strang Lecture](https://www.youtube.com/watch?v=NcPUI7aPFhA)

---