## Special Kinds of Matrices and Tensors

**Diagonal Matrix**
- A diagonal matrix consists mostly of zeros and have nonzero entries only along the main diagonal.
- Identity matrix is a diagonal matrix.

In [1]:
import torch

In [2]:
# Vector containing entries for the diagonal matrix A
x = torch.tensor([2, 4, 6])

# Defining a diagonal matrix A 
A = torch.diag(x)

print(f"Vector x: \n{x}")
print(f"\nDiagonal Matrix A: \n{A}")

Vector x: 
tensor([2, 4, 6])

Diagonal Matrix A: 
tensor([[2, 0, 0],
        [0, 4, 0],
        [0, 0, 6]])


---

**Symmetric Matrix**
- A symmetric matrix is any matrix that is equal to its own transpose.

In [3]:
# Define a matrix

A = torch.tensor([
    [1, 4, 5],
    [4, 2, 6],
    [5, 6, 3]
])

# Take the transpose
A_transpose = torch.transpose(A, 0, 1)

# Check if both are equal, if yes then the matrix is symmetric

print(f"Matrix A: \n{A}")
print(f"\nA_transpose: \n{A_transpose}")

print(f"\nMatrix A is Symmetric: {torch.equal(A, A_transpose)}")

Matrix A: 
tensor([[1, 4, 5],
        [4, 2, 6],
        [5, 6, 3]])

A_transpose: 
tensor([[1, 4, 5],
        [4, 2, 6],
        [5, 6, 3]])

Matrix A is Symmetric: True


---

**Unit Vector**
- A Unit Vector is a vector with Unit Norm.

In [4]:
# Define a unit vector
u = torch.tensor([1], dtype = float)

# Calculate the L2 Norm 
l2_norm = torch.linalg.vector_norm(u, ord = 2)

print(f"L2 Norm of unit vector u: {l2_norm}")
print(f"u is a unit vector: {l2_norm == 1}")

L2 Norm of unit vector u: 1.0
u is a unit vector: True


---

**Orthogonal Vectors**
- A vector `x` and a vector `y` are orthogonal to each other if $$x^T y = 0$$  
- If both vectors have a non zero norm, this means that they are at a 90 degree angle to each other.

In [5]:
# Define 2 vectors
x = torch.tensor([1, 2], dtype=float)
y = torch.tensor([2, -1], dtype=float)

# Obtain x_transpose
x_transpose = torch.t(x)

# Calculate x^T y
print(f"x^T y: {torch.dot(x_transpose, y)}")

x^T y: 0.0


Thus `x` and `y` are orthogonal vectors.

You can find additional examples for othogonal vectors [here](https://www.storyofmathematics.com/orthogona-vector/).

---

**Orthonormal Vectors**
- If the vectors, not only are orthogonal but also have unit norm we call them orthonormal.
- Now that we know that the vectors `x` and `y` are orthogonal, we can obtain the orthonormal vectors \
by normalizing the vectors to have magnitude of 1.

In [6]:
x_normalized = x / (torch.linalg.vector_norm(x, ord = 2))
y_normalized = y / (torch.linalg.vector_norm(y, ord = 2))

print(f"Following are the Orthonormal vectors")
print(f"\nx_normalized: \n{x_normalized}")
print(f"\ny_normalized: \n{y_normalized}")

Following are the Orthonormal vectors

x_normalized: 
tensor([0.4472, 0.8944], dtype=torch.float64)

y_normalized: 
tensor([ 0.8944, -0.4472], dtype=torch.float64)


Learn more [here](https://www.ucl.ac.uk/~ucahmdl/LessonPlans/Lesson10.pdf)

---

**Orthogonal Matrix**
- An orthogonal matrix is a square matrix whose rows are mutually orthonormal and whose columns are mutually orthonormal.
$$A^TA = AA^T = I$$
- This implies that
$$A^{-1}=A^T$$

In [7]:
A = torch.tensor([
    [-1, 0],
    [0, 1]
    ],
    dtype=float
)

A_transpose = torch.transpose(A, 0, 1)

print(f"A^T A: \n{torch.matmul(A_transpose, A)}")
print(f"\nA A^T: \n{torch.matmul(A, A_transpose)}")
print(f"\nIdentity Matrix: \n{torch.eye(2)}")

A^T A: 
tensor([[1., 0.],
        [0., 1.]], dtype=torch.float64)

A A^T: 
tensor([[1., 0.],
        [0., 1.]], dtype=torch.float64)

Identity Matrix: 
tensor([[1., 0.],
        [0., 1.]])


Thus the above equation holds, and the matrix `A` is an orthogonal matrix.  

---

**Additional Resources**
- [Examples](https://byjus.com/maths/orthogonal-matrix/#orthogonal-matrix)
- [Prof Gilbert Strang Lecture](https://www.youtube.com/watch?v=0MtwqhIwdrI)
- [Khan Academy Tutorial](https://www.youtube.com/watch?v=yDwIfYjKEeo)

---