## 2.7 Eigendecomposition

- Eigendecomposition is a matrix decomposition technique in which we decompose a matrix into a set of eigen vectors and eigenvalues.
- An Eigenvector of a square matrix `A` is a non-zero vector `v` such that multiplication by `A` alters only the scale of `v`:
$$Av=\lambda v$$
- The scalar `v` is known as the eigenvalue corresponding to this eigenvector. 
- If a matrix is not square, the eigendecomposition is not defined.

In [1]:
import torch

In [2]:
A = torch.tensor([
    [-6, 3],
    [4, 5]
    ], dtype = float)

eigenvalues, eigenvectors = torch.linalg.eig(A)
    
print(f"Matrix A: \n{A}")
print(f"\nEigen Values: \n{eigenvalues}")
print(f"\nEigen Vectors: \n{eigenvectors}")

Matrix A: 
tensor([[-6.,  3.],
        [ 4.,  5.]], dtype=torch.float64)

Eigen Values: 
tensor([-7.+0.j,  6.+0.j], dtype=torch.complex128)

Eigen Vectors: 
tensor([[-0.9487+0.j, -0.2425+0.j],
        [ 0.3162+0.j, -0.9701+0.j]], dtype=torch.complex128)


- You can find the mathematical calculations for above values[here] (https://www.mathsisfun.com/algebra/eigenvalue.html)
---

**Additional Resources**
- [3Blue1Brown - Eigenvectors and Eigenvalues](https://youtu.be/PFDu9oVAE-g)
- [MIT Linear Algebra PDF](https://math.mit.edu/~gs/linearalgebra/ila0601.pdf)
- [Prof. Gilbert Strang - Lecture](https://www.youtube.com/watch?v=cdZnhQjJu4I)

---