## 2.8 Singular Value Decomposition

- The Singular Value Decomposition is a way to factorize a matrix into singular vectors and singular values.
- We write the matrix `A` as a product of three matrices:
$$A=UDV^T$$
- The matrix `U` and `V` both defined to be orthogonal matrices.
- The matrix `D` is defined to be a diagonal matrix. `D` is not necessarily square.
- The elements along the diagonal of `D` are known as **singular values** of the matrix `A`.
- The columns of `U` are known as the **left-singular vectors**.
- The columns of `V` are known as the **right-singular vectors**.

In [1]:
import torch

Full SVD of a matrix `A` is defined as 
$$A = Udiag(S)V^H$$

In [41]:
A = torch.full((3, 3), 5, dtype=float)

U, S, Vh = torch.linalg.svd(A)

print(f"A: \n{A}")
print(f"\nU: \n{U}")
print(f"\nS: \n{S}")
print(f"\nVh: \n{Vh}")

A: 
tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]], dtype=torch.float64)

U: 
tensor([[-5.7735e-01,  8.1650e-01, -8.7561e-17],
        [-5.7735e-01, -4.0825e-01, -7.0711e-01],
        [-5.7735e-01, -4.0825e-01,  7.0711e-01]], dtype=torch.float64)

S: 
tensor([1.5000e+01, 1.3294e-15, 7.1822e-48], dtype=torch.float64)

Vh: 
tensor([[-0.5774, -0.5774, -0.5774],
        [-0.8165,  0.4082,  0.4082],
        [-0.0000,  0.7071, -0.7071]], dtype=torch.float64)


In [42]:
# Evaluating the above equation, we get matrix A as the result

torch.matmul(torch.matmul(U, torch.diag(S)), Vh)

tensor([[5.0000, 5.0000, 5.0000],
        [5.0000, 5.0000, 5.0000],
        [5.0000, 5.0000, 5.0000]], dtype=torch.float64)

---

**Additional Resources**
- [Prof. Gilbert Strang Lecture](https://www.youtube.com/watch?v=mBcLRGuAFUk)
- [Stochastic Video](https://www.youtube.com/watch?v=CpD9XlTu3ys)

---