## 2.12 Principal Component Analysis

Principal component analysis (PCA) is a popular technique for analyzing large datasets containing a high number of dimensions/features per observation, increasing the interpretability of data while preserving the maximum amount of information, and enabling the visualization of multidimensional data. Formally, PCA is a statistical technique for reducing the dimensionality of a dataset. This is accomplished by linearly transforming the data into a new coordinate system where (most of) the variation in the data can be described with fewer dimensions than the initial data.

[Reference](https://en.wikipedia.org/wiki/Principal_component_analysis)

In [1]:
import torch

In [2]:
A = torch.arange(12, dtype=float).view(4, 3)

U, S, V = torch.pca_lowrank(A)

print(f"Matrix A: \n{A}")
print(f"\nU: \n{U}")
print(f"\nS: \n{S}")
print(f"\nV: \n{V}")

Matrix A: 
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

U: 
tensor([[ 0.6708,  0.0393,  0.2236],
        [ 0.2236,  0.7060, -0.6708],
        [-0.2236,  0.7060,  0.6708],
        [-0.6708,  0.0393, -0.2236]], dtype=torch.float64)

S: 
tensor([11.6190,  0.0000,  0.0000], dtype=torch.float64)

V: 
tensor([[-0.5774,  0.0000,  0.8165],
        [-0.5774, -0.7071, -0.4082],
        [-0.5774,  0.7071, -0.4082]], dtype=torch.float64)


The relation of `(U, S, V)` to PCA is as follows:

- `A` is a data matrix with `m` samples and `n` features

- the `V` columns represent the principal directions

- `S ** 2 / (m - 1)` contains the eigenvalues of `A^T A / (m - 1)` which is the covariance of `A` when `center=True` is provided.

- `matmul(A, V[:, :k])` projects data to the first `k` principal components

[Source](https://pytorch.org/docs/stable/generated/torch.pca_lowrank.html)

---

**Additional Resources**
- [MIT Lecture](https://www.youtube.com/watch?v=WW3ZJHPwvyg)
---